config/routes.rb
KiiraOnew::Application.routes.draw do
  match '/webhooks/gh/pull_request', :to => 'github#create', via: :post

  resources :orders

  devise_for :users

  resources :galleries, path: "galerias" do
  	resources :drawings, path: "desenhos"
  end

  resources :sales, path: "vendas" do 
    resources :products, path: "produtos"
  end
  
  match '/send_mail',          to: 'galleries#send_mail',         via: 'post'
  get 'news',                  to: 'news#index',                  as: :news
  get '/sobre/quem',           to: 'static_page#who',             as: :who
  get '/sobre/oque',           to: 'static_page#what',            as: :what
  get '/sobre/porque',         to: 'static_page#why',             as: :why

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get "sitemaps/:name" => "galleries#sitemaps", format: :xml, as: :sitemaps


  root 'galleries#index'

end

app/models/drawing.rb
class Drawing < ActiveRecord::Base
	extend FriendlyId

	before_save validates :name, presence: true, uniqueness: true
	before_save validates :description, presence: true
	before_save validates :slug, presence: true, uniqueness: true
	before_save validates :gallery, presence: true
	before_save validates :image, presence: true

	friendly_id :name, use: :slugged
	mount_uploader :image, ImageUploader
	belongs_to :gallery

	self.per_page = 16
end

app/controllers/drawings_controller.rb
class DrawingsController < ApplicationController
  before_action :set_drawing, only: [:show]

  # GET /drawings
  # GET /drawings.json
  def index
    @drawings = Drawing.all
  end

  # GET /drawings/1
  # GET /drawings/1.json
  def show
  end

  private
    def set_drawing
      @drawing = Drawing.includes(:gallery).friendly.find(params[:id])
    end
end

app/helpers/drawings_helper.rb
module DrawingsHelper
	def relactions_random_drawings(gallery)
		gallery.drawings.includes(:gallery).order_by_rand.limit(4).all
	end
end

app/views/drawings/show.html.erb
<% content_for :head do %>
  <meta property="og:url" content="<%= url(request.path) %>">
  <meta property="og:site_name" content="Kiira Onew - Digital Art">
  <meta property="og:title" content="<%= "Kiira Onew - #{@drawing.name}" %>">
  <meta property="og:description" content="<%= @drawing.description %>">
  <meta property="og:image" content="<%= @drawing.image_url %>">
  <meta property="og:image:width" content="1280">
  <meta property="og:image:height" content="720">
  <meta property="fb:app_id" content="653396958070822">
  <%= stylesheet_link_tag "lightbox", :media => "all", defer: true %>
  <%= javascript_include_tag "lightbox", "data-turbolinks-track" => true, defer: true %>
<% end %>
<div class="container">
    <p id="notice"><%= notice %></p>
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header" style="margin-top: 0px;"><%= @drawing.name%>
                <small>(<%= @drawing.gallery.name%>)</small>
                <a href="<%= gallery_path(@drawing.gallery)%>" class="btn btn-default btn-primary pull-right"><span class="glyphicon glyphicon-arrow-left"></span> Voltar para <%= @drawing.gallery.name%></a>

            </h1>
        </div>

        <div class="col-md-8">
            <a href=<%= @drawing.image_url%> data-lightbox="lightbox" data-title=<%= @drawing.name%> ><%= image_tag(@drawing.image_url, class: "img-responsive",size: "500,750") %></a>           
            </a>
        </div>
        <div class="col-md-4">
            <h3>Descrição</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae. Sed dui lorem, adipiscing in adipiscing et, interdum nec metus. Mauris ultricies, justo eu convallis placerat, felis enim.</p>
            
            <h3>Compartilhe:</h3>
            <a href="#" onClick="<%= "window.open('http://www.pinterest.com/pin/create/bookmarklet/?media=#{@drawing.image_url}&url=#{request.original_url}&is_video=false&description=#{@drawing.name}','sharer','toolbar=0,status=0,width=580,height=325');"%>"><img class="image-pinterest"></a>
            <a href="#" onClick="<%= "window.open('http://www.facebook.com/share.php?u=#{request.original_url}','sharer','toolbar=0,status=0,width=580,height=325');"%>"><img class="image-facebook"></a>
            <a href="#" onClick="<%= "window.open('https://plus.google.com/share?url=#{request.original_url}','sharer','toolbar=0,status=0,width=580,height=325');"%>"><img class="image-googleplus"></a>
            <a href="#" onClick="<%= "window.open('https://twitter.com/intent/tweet?hashtags=MakeArt%2C&original_referer=#{request.original_url}%2F&text=Gostei%20da%20ilustração%20#{@drawing.name}%20feita%20por%20@kiira_Onew%20-%20O%20Kiira%20Onew&tw_p=tweetbutton&url=#{request.original_url}&via=kiira_Onew','sharer','toolbar=0,status=0,width=580,height=325');"%>"><img class="image-twitter"></a>
            <a href="#" onClick="window.open('http://www.tumblr.com/share/photo?source=<%=u @drawing.image_url %>&caption=<%=u "#{link_to @drawing.name, gallery_drawing_path(@drawing.gallery, @drawing)} by #{link_to "Kiira Onew", "http://kiiraonew.deviantart.com"} "%>&clickthru=<%=u request.original_url %>','sharer','toolbar=0,status=0,width=580,height=325');"><img class="image-tumblr"></a>
            <h3>Visite meu perfil no Deviantart</h3>
            <a href="http://kiiraonew.deviantart.com/" target="_blank"><%= image_tag("deviantart-banner.png", class: "img-responsive") %></a>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <h3 class="page-header">Relacionados</h3>
        </div>

        <% relactions_random_drawings(@drawing.gallery).each do |drawing|%>
            <%= link_to gallery_drawing_path(drawing.gallery, drawing), class: "link-not-decorate" do %> 
                <div class="col-sm-3 col-xs-6 portfolio-item">
                    <%= image_tag(drawing.image_url(:thumb), class: "img-responsive img-thumbnail") %>
                </div>
            <% end %>
        <% end %>
    </div>
    <br/>

    <div class="row">
        <div class="col-lg-12">
    <h3><a href="<%=request.original_url%>#disqus_thread" class="link-not-decorate">Diga-me o que achou do <%= @drawing.name %> nos comentários abaixo</a></h3>
     </div>
    </div>
     <div id="disqus_thread"></div>
        <script type="text/javascript">
            /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
            var disqus_shortname = 'kiiraonew'; // required: replace example with your forum shortname

            /* * * DON'T EDIT BELOW THIS LINE * * */
            (function() {
                var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
                dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
                (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
            })();
        </script>
        <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
        <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>

</div>