config/routes.rb
KiiraOnew::Application.routes.draw do
  match '/webhooks/gh/pull_request', :to => 'github#create', via: :post

  resources :orders

  devise_for :users

  resources :galleries, path: "galerias" do
  	resources :drawings, path: "desenhos"
  end

  resources :sales, path: "vendas" do 
    resources :products, path: "produtos"
  end
  
  match '/send_mail',          to: 'galleries#send_mail',         via: 'post'
  get 'news',                  to: 'news#index',                  as: :news
  get '/sobre/quem',           to: 'static_page#who',             as: :who
  get '/sobre/oque',           to: 'static_page#what',            as: :what
  get '/sobre/porque',         to: 'static_page#why',             as: :why

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get "sitemaps/:name" => "galleries#sitemaps", format: :xml, as: :sitemaps


  root 'galleries#index'

end

app/models/drawing.rb
class Drawing < ActiveRecord::Base
	extend FriendlyId

	before_save validates :name, presence: true, uniqueness: true
	before_save validates :description, presence: true
	before_save validates :slug, presence: true, uniqueness: true
	before_save validates :gallery, presence: true
	before_save validates :image, presence: true

	friendly_id :name, use: :slugged
	mount_uploader :image, ImageUploader
	belongs_to :gallery

	self.per_page = 16
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
	extend FriendlyId

	before_save validates :name, presence: true, uniqueness: true
	before_save validates :description, presence: true
	before_save validates :slug, presence: true, uniqueness: true
	before_save validates :image, presence: true

	friendly_id :name, use: :slugged
	mount_uploader :image, ImageUploader
	has_many :drawings
end

app/models/news.rb
class News < ActiveRecord::Base
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :product
end

app/models/product.rb
class Product < ActiveRecord::Base
  	belongs_to :sale
	extend FriendlyId

	before_save validates :name, :image, :description, :price, :stock, presence: true

	friendly_id :name, use: :slugged
	mount_uploader :image, ImageUploader
end

app/models/sale.rb
class Sale < ActiveRecord::Base
	extend FriendlyId
	has_many :products
	friendly_id :name, use: :slugged

	mount_uploader :image, ImageUploader

	scope :latest,   ->{ order(updated_at: :desc).limit(4) }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/drawings_controller.rb
class DrawingsController < ApplicationController
  before_action :set_drawing, only: [:show]

  # GET /drawings
  # GET /drawings.json
  def index
    @drawings = Drawing.all
  end

  # GET /drawings/1
  # GET /drawings/1.json
  def show
  end

  private
    def set_drawing
      @drawing = Drawing.includes(:gallery).friendly.find(params[:id])
    end
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  before_action :set_gallery, only: [:show]

  # GET /galleries
  # GET /galleries.json
  def index
    @galleries = Gallery.all
  end

  # GET /galleries/1
  # GET /galleries/1.json
  def show
  end

  def send_mail
    name = params[:name]
    email = params[:email]
    message = params[:comments]
    UserMailer.contact_me(name, email, message).deliver
    flash[:success] = "Email enviado com sucesso! Obrigado!"
    redirect_to root_path
  end
  
  def sitemaps
    path = Rails.root.join("app", "sitemaps", "#{params[:name]}.xml")
    if File.exists?(path)
      render xml: open(path).read
    else
      render text: "Sitemap not found.", status: :not_found
    end
  end

  private
    def set_gallery
      @gallery = Gallery.friendly.find(params[:id])
    end
end

app/controllers/github_controller.rb
class GithubController < ApplicationController
  skip_before_filter
  protect_from_forgery :except => :create

  def create
    hash = JSON.parse(params[:payload])
    render :json => hash
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  def index
  	@news = News.all
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render action: 'show', status: :created, location: @order }
      else
        format.html { render action: 'new' }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:user_name, :user_mail, :product_id, :facebook_contact)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.friendly.find(params[:id])
    end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy]

  # GET /sales
  # GET /sales.json
  def index
    @sales = Sale.all
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.friendly.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def title(page_title)
  		content_for(:title) { page_title }
	end

	def google_analytics
    if Rails.env.development?
    '<!-- GOOGLE ANALYTICS should be here -->'.html_safe

    '<!-- GOOGLE ANALYTICS should be here -->'.html_safe
    else
      render 'partials/google_analytics'
    end
  end

  def url(*paths, domain: SETTINGS[:main_domain], protocol: 'http', **options)
    paths[0] = paths.first[1..-1] if paths.first && paths.first[0] == '/'
    url = protocol ? ["#{protocol}://#{domain}", *paths].join('/') : [domain, *paths].join('/')
    url.gsub('.json', '')
  end
end

app/helpers/drawings_helper.rb
module DrawingsHelper
	def relactions_random_drawings(gallery)
		gallery.drawings.includes(:gallery).order_by_rand.limit(4).all
	end
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
	def relactions_random_sales
		Product.all.includes(:sale).order_by_rand.limit(4).all
	end
end

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Kiira Onew" %>">
        <%= stylesheet_link_tag "devise", media: "all", "data-turbolinks-track" => true, defer: true %>
        <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true, defer: true %>
        <%= csrf_meta_tags %>
    </head>
    <body>
        <div class="container">
        <%= yield %>  
        </div>
    </body>
</html>

app/views/layouts/superhero.html.erb
<!DOCTYPE html>
<html lang="pt" itemscope itemtype="http://schema.org/Product">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="canonical" href="<%= url(request.path) %>">
    <%= javascript_include_tag "jquery-1.11.0", "data-turbolinks-track" => true, defer: true  %>
    <title> <%= content_for?(:title) ? yield(:title) : "Kiira Onew Designer" %></title>
    <meta name="google-site-verification" content="i0MWxJAcu-753fhaNKh8pWit_eX2_qaoMvjThFCaSa0" />
    <%= csrf_meta_tags %>
    <%= yield :head %>
<script type="text/javascript">var _kmq = _kmq || [];
    var _kmk = _kmk || '3dda54e0d325ffcd81be208a7071c453d36595a3';
    function _kms(u){
      setTimeout(function(){
        var d = document, f = d.getElementsByTagName('script')[0],
        s = d.createElement('script');
        s.type = 'text/javascript'; s.async = true; s.src = u;
        f.parentNode.insertBefore(s, f);
      }, 1);
    }
    _kms('//i.kissmetrics.com/i.js');
    _kms('//doug1izaerwt3.cloudfront.net/' + _kmk + '.1.js');
    </script>
    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "superhero", :media => "all", defer: true %>
    <%= google_analytics %>

  </head>
  <body>
        <%= render 'partials/navigation' %>
        
        <%= yield %>
            
        <div class="container">
            <%= render 'partials/footer'%>
        </div>

        <a href="javascript:" id="return-to-top" role="button" title="Click para retornar ao topo da pagina" data-toggle="tooltip" data-placement="left"><i class="fa fa-chevron-up"></i></a>


        <%= javascript_include_tag "superhero", defer: true %>
  </body>
</html>

app/views/partials/_contact_me.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="page-header">
      <h1 id="forms">Entre em contato <i class="fa fa-fw fa-send"></i></h1>
    </div>
  </div>
</div>
<div class="row">
    <div class="col-lg-8 col-md-8 col-sm-7 col-xs-12">
        <%= form_tag send_mail_path, validate: true,  html: {class: "form"} do |f| %>                
            <div class="row">
                <div class="col-lg-6">
                    <div class="form-group">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="fa fa-fw fa-user"></i></span>
                            <%= text_field_tag :name, nil, placeholder: "Informe seu nome", class: "form-control", :required => true %>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="input-group">
                            <span class="input-group-addon">@</span>
                            <%= text_field_tag :email, nil,  placeholder: "Informe seu email", class: "form-control", :required => true, type: "email" %>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="fa fa-fw fa-book"></i></span>
                            <%= text_field_tag :subject, nil,  placeholder: "Assunto", class: "form-control", :required => true, type: "text" %>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="form-group">
                        <%= text_area_tag :message, nil, class: "form-control", placeholder: "Por favor escreva sua mensagem aqui...", rows: "3", :required => true %>
                    </div>
                    <%= submit_tag "Enviar Mensagem", class: "btn btn-block btn-primary pull-right", style: "background-color:rgba(223,105,26,0.8);" %>
                </div>
            </div>
        <% end %>
    </div>
    <div class="col-lg-4">
          <p style="font-size: 24px">kiira_onew@gmail.com <i class="fa fa-fw fa-envelope"></i></p>
          <p style="font-size: 24px">+55 12 98274-7616 <i class="fa fa-fw fa-phone"></i></p>
          <p style="font-size: 24px"><a href="skype:kiira_onew?userinfo" style="color:white">Kirra Onew</a> <i class="fa fa-fw fa-skype"></i></p>
        
    </div>
  </div>

app/views/partials/_footer.html.erb
<div class="row" style="font-size: 8px">
  <div class="col-lg-12">          
    <div class="panel panel-default">
      <div class="panel-body">
      <div class="col-md-4">          
            <h4 class="text-info">Like Me on Facebook</h4>
            <ul class="nav">
              <iframe src="//www.facebook.com/plugins/likebox.php?href=http%3A%2F%2Fwww.facebook.com%2Fkiiraonewartworks&amp;width=289&amp;height=258&amp;colorscheme=dark&amp;show_faces=true&amp;header=false&amp;stream=false&amp;show_border=false&amp;data-width=auto" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:289px; height:258px;" allowTransparency="true"></iframe>
            </ul> 
          </div>
          <div class="col-md-4 col-xs-6">          
            <h4 class="text-info">Siga-me</h4>
              <h4> <a href="about-us.html"><i class="fa fa-fw fa-deviantart" style="color: #bdd023"></i> DeviantArt</a> </h4>
              <h4> <a href="about-us.html"><i class="fa fa-fw fa-twitter" style="color: #00A0D1;"></i> Twitter</a> </h4>
              <h4> <a href="about-us.html"><i class="fa fa-fw fa-facebook" style="color: #3B5998;"></i> Facebook</a> </h4>
              <h4> <a href="about-us.html"><i class="fa fa-fw fa-google-plus" style="color: #dd4b39;"></i> Google</a> </h4>
              <h4> <a href="about-us.html"><i class="fa fa-fw fa-pinterest" style="color: #cb2027;"></i> Pinterest</a> </h4>
              <h4> <a href="about-us.html"><i class="fa fa-fw fa-youtube-play" style="color: #bb0000;"></i> Youtube</a> </h4>
              <h4> <a href="about-us.html"><i class="fa fa-fw fa-instagram" style="color:#517fa4;"></i> Instagram</a> </h4>
              <h4> <a href="about-us.html"><i class="fa fa-fw fa-tumblr" style="color: #32506d;"></i>Tumblr</a> </h4>
          </div>
          <div class="col-md-4">          
            <h4 class="text-info">Site</h4>
            <h5><a href="about-us.html">Home</a></h5>
            <h5><a href="about-us.html">Galleries</a></h5>
            <h5><a href="about-us.html">News</a></h5>
            <h4 class="text-info">Customer Service</h4>
            <h5><a href="about-us.html">About Us</a></h5>
            <h5><a href="about-us.html">Delivery Information</a></h5>
            <h5><a href="about-us.html">Privacy Policy</a></h5>
            <h5><a href="about-us.html">Terms &amp; Conditions</a></h5>
          </div>
          
      </div>
    </div>
  </div>
</div>

app/views/partials/_google_analytics,html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-54266208-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/partials/_google_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-54266208-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/partials/_hero.html.erb
<div class="row">
	<div class="col-lg-12">	
		<div class="jumbotron">
			<h1>Kiira Onew</h1>
			<p><%= hero_info %></p>                
			<p><a class="btn btn-primary btn-lg">Leia mais</a></p>
		</div>
	</div>
</div>

app/views/partials/_infos_about.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="page-header">
      <h1 id="type">Algumas coisas sobre mim e meu trabalho <i class="fa fa-tasks"></i></h1>
    </div>
  </div>
</div>
<div class="row destacados">
  <div class="col-md-4">
    <div>      
      <%= image_tag("profile.jpg", size: "200x200", class: "img-circle img-thumbnail") %>
      <h2>Quem sou eu? <i class="fa fa-question"></i></h2> 
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
      tempor incididunt ut labore et dolore magna aliqua.</p>
      <a href=<%= who_path %> class="btn btn-primary" title="Enlace">Leia Mais »</a>
    </div>
  </div>
  <div class="col-md-4">
    <div>
      <%= image_tag("work.jpg", size: "200x200", class: "img-circle img-thumbnail") %>
      <h2>O que eu faço? <i class="fa fa-question"></i></h2>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
      tempor incididunt ut labore et dolore magna aliqua.</p>
      <a href=<%= what_path %> class="btn btn-primary" title="Enlace">Leia mais »</a>
    </div>
  </div>
  <div class="col-md-4">
    <div>
      <%= image_tag("why.jpg", size: "200x200", class: "img-circle img-thumbnail") %>
      <h2>Por que eu faço? <i class="fa fa-question"></i></h2>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
      tempor incididunt ut labore et dolore magna aliqua.</p>
      <a href=<%= why_path %> class="btn btn-primary" title="Enlace">Leia mais »</a>
    </div>
  </div>
</div>

app/views/partials/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/partials/_navigation.html.erb
<div class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <a href=<%= "#{request.scheme}://#{request.host_with_port}#{request.script_name}" %> class="navbar-brand"><i class="fa fa-home"></i> Kiira Onew</a>
      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar-main">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#"><i class="fa fa-picture-o"></i> Galerias <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% Gallery.all.each do | gallery |%>
            <li><a href=<%=gallery_path(gallery)%>> <%= gallery.name %></a></li>
            <% end %>
          </ul>
        </li>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#" ><i class="fa fa-external-link"></i> Redes Sociais <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="http://kiiraonew.deviantart.com/">DeviantArt</a></li>
            <li><a href="https://www.facebook.com/kiiraonewartworks">Facebook</a></li>
            <li><a href="https://twitter.com/kiiraonew">Twitter</a></li>
            <li><a href="https://www.youtube.com/channel/UCZtDSKPuxKn68ktw7kwGSWQ">YouTube</a></li>
            <li><a href=".http://itskiiraonewartworks.tumblr.com/">Tumblr</a></li>
            <li><a href="./bootstrap.css">Google +</a></li>
           </ul>
        </li>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#"><i class="fa fa-info-circle"></i> Sobre mim <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href=<%= who_path %>>Quem sou eu</a></li>
            <li><a href=<%= what_path %>>O que eu faço</a></li>
            <li><a href=<%= why_path %>>Por que eu faço</a></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="http://builtwithbootstrap.com/" target="_blank"><i class="fa fa-envelope"></i> Subscribe to newsletter</a></li>
        <li><a href="https://wrapbootstrap.com/?ref=bsw" target="_blank">WrapBootstrap</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/partials/_sales.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="page-header">
      <h1 id="forms">Á venda <i class="fa fa-send"></i></h1>
    </div>
  </div>
</div>
<% Sale.all.each do |sale| %>
	<div class="row">
	    <div class="col-md-3">
	        <div class="col-item">
	            <div class="photo">
	                <%= image_tag(sale.image_url(:fit), class: "img-responsive" ) if sale.image? %>
	            </div>
	            <div class="info text-center">
	                <div class="row">
	                    <div class="col-md-12">
	                        <h4 class="text-primary" >
	                            <%= sale.name %>
	                        </h4>
	                    </div>
	                    <div class="col-md-12">
	                        <p class="text-info">
	                        	<%= sale.description %>
	               			</p>
	                    </div>
	                    <hr width="60%" style="margin-bottom: 3px">
	                    
	                    <div class="col-md-12"  style="margin-bottom: 5px">
	                        <h4>Á partir de</h4>
	                        <h3 class="text-success" style="display:inline"><strong>R$ <%= sale.starting %></strong></h3>
	                    </div>

	                </div>
	                <div class="btn btn-primary btn-block"><%= link_to "Veja mais", sale_path(sale), class: "link-not-decorate" %></div>
	            </div>
	        </div>
	    </div>
	</div>
<% end %>