config/routes.rb
KiiraOnew::Application.routes.draw do
  match '/webhooks/gh/pull_request', :to => 'github#create', via: :post

  resources :orders

  devise_for :users

  resources :galleries, path: "galerias" do
  	resources :drawings, path: "desenhos"
  end

  resources :sales, path: "vendas" do 
    resources :products, path: "produtos"
  end
  
  match '/send_mail',          to: 'galleries#send_mail',         via: 'post'
  get 'news',                  to: 'news#index',                  as: :news
  get '/sobre/quem',           to: 'static_page#who',             as: :who
  get '/sobre/oque',           to: 'static_page#what',            as: :what
  get '/sobre/porque',         to: 'static_page#why',             as: :why

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get "sitemaps/:name" => "galleries#sitemaps", format: :xml, as: :sitemaps


  root 'galleries#index'

end

app/models/sale.rb
class Sale < ActiveRecord::Base
	extend FriendlyId
	has_many :products
	friendly_id :name, use: :slugged

	mount_uploader :image, ImageUploader

	scope :latest,   ->{ order(updated_at: :desc).limit(4) }
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy]

  # GET /sales
  # GET /sales.json
  def index
    @sales = Sale.all
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.friendly.find(params[:id])
    end
end

app/helpers/sales_helper.rb
module SalesHelper
	def relactions_random_sales
		Product.all.includes(:sale).order_by_rand.limit(4).all
	end
end

app/views/sales/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <h1 class="page-header" style="margin-top: 0px;">Produtos <i class="fa fa-send"></i></h1>
    </div>
  </div>
</div>
<% @sale.products.each do |product| %>
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <div class="col-item">
          <div class="photo">
              <%= image_tag(product.image_url(:fit), class: "img-responsive" ) if product.image? %>
          </div>
          <div class="info text-center">
              <div class="row">
                  <div class="col-md-12">
                      <h4 class="text-primary"><%= product.name %></h4>
                  </div>
                  <div class="col-md-12">
                      <p class="text-info">Canecas personalizadas com desenhos diversos</p>
                  </div>
                  <hr width="60%" style="margin-bottom: 3px">
                  <div class="col-md-12 pull-right"  style="margin-bottom: 5px">
                      <h4>Preço</h4>
                      <h3 class="text-success" style="display:inline"><strong>R$ <%= product.price %></strong></h3>
                  </div>
              </div>
              <button type="button" class="btn btn-primary btn-block" data-toggle="modal" data-target="#myModal">
                  Pedir
                </button>

                <!-- Modal -->
                <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                  <div class="modal-dialog">
                    <div class="modal-content">
                      <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                        <h4 class="modal-title" id="myModalLabel">Novo Pedido</h4>
                      </div>
                      <div class="modal-body">
                        <%= form_for Order.new, :html => { :class => 'form-horizontal' } do |f| %>
                          <fieldset>
                            <legend>Informações</legend>
                            <div class="form-group">
                              <%= f.label :user_name, "Nome", :class => 'col-lg-2 control-label' %>
                              <div class="col-lg-10">
                                <%= f.text_field :user_name, :class => 'form-control', placeholder: "Digite seu nome..." %>
                              </div>
                            </div>
                            <div class="form-group">
                              <%= f.label :user_mail, "Email",:class => 'col-lg-2 control-label', for: "inputEmail" %>
                              <div class="col-lg-10">
                                <%= f.text_field :user_mail, :class => 'form-control', id: "inputEmail", placeholder: "Digite seu email..." %>
                              </div>
                            </div>
                              <%= f.hidden_field :product_id, :class => 'form-control', value: "#{product.id}" %>
                            <div class="form-group">
                              <%= f.label :facebook_contact, "Facebook", :class => 'col-lg-2 control-label' %>
                              <div class="col-lg-10">
                                <%= f.text_field :facebook_contact, :class => 'form-control', placeholder: "Ex: www.facebook.com/kiira.onew" %>
                              </div>
                            </div>
                        
                            <div class="modal-footer">
                              <%= f.submit "Enviar Pedido", :class => 'btn btn-primary' %>
                              <%= link_to "Cancelar", orders_path, class: "btn btn-default", :'data-dismiss' => "modal", style: "background-color: #b20000" %>
                            </div>
                          </fieldset>
                        <% end %>
                    </div>
                  </div>
                </div>
              </button>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

<div class="container">
  <div class="row">
      <div class="col-lg-12">
          <h3 class="page-header">Outros Produtos</h3>
      </div>

      <% relactions_random_sales.each do |product|%>
          <%= link_to sale_path(product.sale), class: "link-not-decorate" do %> 
              <div class="col-sm-3 col-xs-6 portfolio-item">
                  <%= image_tag(product.image_url(:fit), class: "img-responsive img-thumbnail") %>
              </div>
          <% end %>
      <% end %>
  </div>
</br>
</div>